environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    # - PYTHON: "C:\\Python27"
    # - PYTHON: "C:\\Python33"
    # - PYTHON: "C:\\Python34"
    # - PYTHON: "C:\\Python35"
    # - PYTHON: "C:\\Python27-x64"
    # - PYTHON: "C:\\Python33-x64"
    #   DISTUTILS_USE_SDK: "1"
    # - PYTHON: "C:\\Python34-x64"
    #   DISTUTILS_USE_SDK: "1"
    # - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install pytest pytest-randomly pytest-cov psutil pyftpdlib mock"
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest -v tests"
