name: Package

on:
  - push
  - pull_request

jobs:

  build-wheel:
    runs-on: ubuntu-latest
    name: Build wheel distribution
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update build dependencies
      run: python -m pip install -U pip wheel setuptools
    - name: Build wheel distribution
      run: python setup.py bdist_wheel
    - name: Store built wheel
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*

  build-sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update build dependencies
      run: python -m pip install -U pip wheel setuptools
    - name: Build source distribution
      run: python setup.py sdist
    - name: Store source distribution
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*

  test-sdist:
    runs-on: ubuntu-latest
    name: Test source distribution
    needs:
      - build-sdist
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Download source distribution
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist
    - name: Install source distribution
      run: python -m pip install dist/fs-*.tar.gz
    - name: Remove source code
      run: rm -rvd fs
    - name: Install test requirements
      run: python -m pip install -r tests/requirements.txt
    - name: Test installed package
      run: python -m unittest discover -vv

  test-wheel:
    runs-on: ubuntu-latest
    name: Test wheel distribution
    needs:
      - build-wheel
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Download source distribution
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist
    - name: Install source distribution
      run: python -m pip install dist/fs-*.whl
    - name: Remove source code
      run: rm -rvd fs
    - name: Install test requirements
      run: python -m pip install -r tests/requirements.txt
    - name: Test installed package
      run: python -m unittest discover -vv

  upload:
    environment: PyPI
    runs-on: ubuntu-latest
    name: Upload
    needs:
    - build-sdist
    - build-wheel
    - test-sdist
    - test-wheel
    steps:
    - name: Download built distributions
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist
    - name: Publish distributions to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: false
